### ISSUE TITLE
yo  github io links didnt get blocked our names got put on a banlist with githubio too so our pages might be safe

### ISSUE THREAD

**Issue by Realhack1** [TrickJoker312/Unblocked-Sites#22]
also onreader links should be banned cause there just gonna expire in a couple days and people dont redeploy them

**Comment by TrickJoker312** [comment]
Wait, what? What do you mean?
also sorry for replying late :(

**Comment by TrickJoker312** [comment]
Did GitHub put us on a banlist?

**Comment by Realhack1** [comment]
no our schoolboard our github io links are  blocked but not others like outred

**Comment by TrickJoker312** [comment]
I'll check

**Comment by TrickJoker312** [comment]
I get about 28k people coming to this repo a month, with about 1k - 2k people coming here a day.

**Comment by TrickJoker312** [comment]
:/

**Comment by TrickJoker312** [comment]
does traffic have anything to do with me being banned from github.io links?

**Comment by TrickJoker312** [comment]
Oh, yeah.

**Comment by Realhack1** [comment]
more traffic more of a chance to  be discoved by teachers and stuff

**Comment by Realhack1** [comment]
Also are you on a stream or A All for one computor at school

**Comment by TrickJoker312** [comment]
i am not understanding :(
My school computer is right here: https://www.dell.com/ae/business/p/chromebook-11-3100-laptop/pd

**Comment by Realhack1** [comment]
are you on a laptop or a inmoble computor

**Comment by TrickJoker312** [comment]
oh :/
A laptop

**Comment by TrickJoker312** [comment]
Oh, okay.

**Comment by Realhack1** [comment]
alr also find all proxies links into a txt file just in case

**Comment by TrickJoker312** [comment]
Okay.

**Comment by TrickJoker312** [comment]
Also what other websites could i store this code into?

**Comment by Realhack1** [comment]
anyy
