### ISSUE TITLE
Contact Discord username?

### ISSUE THREAD

**Issue by Deus-Scissuras** [TrickJoker312/Unblocked-Sites#24]
I have a amazing idea I Want to share in private 
My discord is Project Goggle Dev

**Comment by Thedogecraft** [comment]
That discord username did not wo can you verify that its correct (ProjectGoggleDev)

**Comment by Deus-Scissuras** [comment]
changed it sorry Its now my github user

**Comment by Deus-Scissuras** [comment]
@TrickJoker312 you die?

**Comment by Thedogecraft** [comment]
![image](https://github.com/TrickJoker312/Unblocked-Sites/assets/97050087/00e4270d-05d4-4dc5-abc3-c7a2148882db)

**Comment by Deus-Scissuras** [comment]
Just give
Me ura

**Comment by Deus-Scissuras** [comment]
Urs

**Comment by Thedogecraft** [comment]
dogecraft

**Comment by Deus-Scissuras** [comment]
Added
