### ISSUE TITLE
Dude

### ISSUE THREAD

**Issue by FancyBoiL1** [TrickJoker312/Unblocked-Sites#3]
Why would a bunch of the links you have here? You are going to get them blocked, just because of that! Some\Multiple schools have IT teams that search github for game sites, and block the links manually. That's one of the reasons that the site developers are ignoring you when you ask for sites.

**Comment by TrickJoker312** [comment]
I'm sorry you disagree with my intentions. I'm just trying to give people a fun and enjoyable time at school! If you'd like to recommend a site, please let me know.

Have a good day!

**Comment by TrickJoker312** [comment]
@
