### ISSUE TITLE
Takedown Notice

### ISSUE THREAD

**Issue by Asleep123** [TrickJoker312/Unblocked-Sites#34]
Hi. I manage Art Class. I do notice that you have some of our private links on this document. We request that you take down this GitHub repo in the next 48h or action will be taken.

**Comment by TrickJoker312** [comment]
Hello! Do you mind telling me which links are yours?

**Comment by Asleep123** [comment]
There is an open pull request that contains one of our links. Can you delete that PR? Not close it,  but delete it.

**Comment by Asleep123** [comment]
Just close it, then.
