### ISSUE TITLE
This ->

### ISSUE THREAD

**Issue by FancyBoiL1** [TrickJoker312/Unblocked-Sites#4]
I'm sorry you disagree with my intentions. I'm just trying to give people a fun and enjoyable time at school! If you'd like to recommend a site, please let me know.

Have a good day!

_Originally posted by @TrickJoker312 in https://github.com/TrickJoker312/Unblocked-Sites/issues/3#issuecomment-1419205953_
            
           I don't have any problem with this, I was making a statement. 
           
           Proof: https://docs.google.com/document/d/1CS_m6uzIbYgtQs7taX4KuffJ86J_rUBjcbzn4m8Dao8/

**Comment by FancyBoiL1** [comment]
Idc, just not all of them.

**Comment by TrickJoker312** [comment]
Ok, thank you! I appreciate it

**Comment by FancyBoiL1** [comment]
Np
