### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by J7DT2023** [TrickJoker312/Unblocked-Sites#42]
Umm hey Trickjoker I was wondering if you  had any new sites to add cause most didn't work for me ik you just updated it so whenever you find anything could you pls dm me it'd be much appreciated if you send a site with an internet browser as well

**Comment by TrickJoker312** [comment]
Hey!

I'll be adding more websites soon, so be sure to be on lookout for those! In the meantime, if you have Discord, you can join various proxies discord servers [for example, Interstellar] for more links while you wait.

**Comment by J7DT2023** [comment]
woah that was a fast reply didn't expect you to write back so quickly but anyways thanks for addressing me, sry for wasting your time and have a great rest of your day!

**Comment by TrickJoker312** [comment]
No problem! I address every issue i get :) 
Also, i get emails from GitHub about issues in my repositories, so that's why I responded so quickly!
You have a great rest of your day, too!
