### ISSUE TITLE
More websites(might be duplicates for some)

### ISSUE THREAD

**Issue by fartsindogs** [TrickJoker312/Unblocked-Sites#6]
Check this website for proxys
https://sites.google.com/view/bypass-central/home

Theres also 
https://a-karen-is-tricky-to-an-employee-to-understand.glitch.me
https://nothing-that-does-something-i-guess.glitch.me
https://chhssssssss.glitch.me
https://a-ken-and-karen-are-both-mean.glitch.me
https://connor-is-a-salty-ken.glitch.me
https://uwu-says-ur-mom.glitch.me

Your welcome :)

**Comment by fartsindogs** [comment]
Also i feel like just doing a pull request is easier for me and you

**Comment by TrickJoker312** [comment]
Thanks!

**Comment by TrickJoker312** [comment]
Hey... Someone put these links in their repository... The repository is a copy of mine. Anything you can do about it, like contact them to try to get it off? The guy literally took every link I had. This Is his repository... https://github.com/Realhack101/Realhack101-s-Unblocked-Games

**Comment by Realhack101** [comment]
a copy is funny a upgrade is a better word.

**Comment by TrickJoker312** [comment]
How is it an upgrade if my repository has more links.... There's no point in stealing ideas. I'm sure you have fantastic ideas in your head, just don't copy mine in the process.

**Comment by TrickJoker312** [comment]
I would appreciate it if you could please stop copying from me. I'm sure you can find links on your own. I would also appreciate it if you could delete every link you took from me in the repository.

**Comment by Realhack101** [comment]
I have and had my own code for the other stuff mine work for me and others yours most for me dont work i made my repo then found yours

**Comment by TrickJoker312** [comment]
Okay, but just please don't copy my repository.

**Comment by Realhack101** [comment]
its not a copy you don't own those links by putting them in your repo

**Comment by Realhack101** [comment]
if you contact me i will do something abt it

**Comment by fartsindogs** [comment]
Then I will

**Comment by fartsindogs** [comment]
bruh you cant report somone for stealing code

**Comment by fartsindogs** [comment]
oh and you have a CCO licence so you can do much

**Comment by fartsindogs** [comment]
oh and do you have a discord

**Comment by TrickJoker312** [comment]
Yes, but i forgot the tag.

**Comment by fartsindogs** [comment]
go check

**Comment by TrickJoker312** [comment]
I can't, i'm in school.
